name: AdventureExpansion
version: '${version}'
main: me.coopersully.rpgloot.rpgloot.AdventureExpansion
api-version: 1.20
authors: [ coopersully ]
description: A plugin that adds roleplay-themed items, blocks, and game mechanics.
website: https://github.com/coopersully/adventure-expansion/

commands:
  meta:
    description: Get the meta-data of the held treasure item.
    #aliases: []
  cleanse:
    description: Cleanse the held treasure item if applicable.
    #aliases: []
  nightmare:
    description: Infuse the held item with Nightmare Fuel if applicable.
    aliases: [ "nightmarify" ]
  trades:
    description: Access all trades-related data.
    #aliases: []
  givetreasure:
    description: Gives the player a specified treasure item.
    aliases: [ "givetreasureitem", "givet", "gt" ]
  listtreasure:
    description: Lists all defined treasure items.
    aliases: [ "listtreasureitems", "listtreasureitem", "listt", "lt" ]