name: AdventureExpansion
version: '${version}'
main: me.coopersully.rpgloot.rpgloot.AdventureExpansion
api-version: 1.20
authors: [ coopersully ]
description: A plugin that adds roleplay-themed items, blocks, and game mechanics.
website: https://github.com/coopersully/adventure-expansion/

commands:
  adventureexpansion:
    description: Base command for Adventure Expansion
    aliases: [ "ae" ]
  meta:
    description: Get the meta-data of the held treasure item.
    #aliases: []
  cleanse:
    description: Cleanse the held treasure item if applicable.
    #aliases: []
  nightmare:
    description: Infuse the held item with Nightmare Fuel if applicable.
    aliases: [ "nightmarify" ]
  trades:
    description: Access all trades-related data.
    #aliases: []
  treasure:
    description: All things treasure-related.
    aliases: [ "tr", "t" ]