package me.coopersully.rpgloot.rpgloot.items.treasure_items;

import me.coopersully.rpgloot.rpgloot.AdventureExpansion;
import org.bukkit.NamespacedKey;

public class TreasureItemKeys {

    public static NamespacedKey treasureItem = new NamespacedKey(AdventureExpansion.getPlugin(), "treasure_item");
    public static NamespacedKey cleansed = new NamespacedKey(AdventureExpansion.getPlugin(), "cleansed");
    public static NamespacedKey greedTools = new NamespacedKey(AdventureExpansion.getPlugin(), "greed");
    public static NamespacedKey nightmareFuel = new NamespacedKey(AdventureExpansion.getPlugin(), "nightmare_fuel");
    public static NamespacedKey nightmare = new NamespacedKey(AdventureExpansion.getPlugin(), "nightmare");
    public static NamespacedKey traveler = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler");
    public static NamespacedKey raider = new NamespacedKey(AdventureExpansion.getPlugin(), "raider");
    public static NamespacedKey awakened = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened");
    public static NamespacedKey eternal = new NamespacedKey(AdventureExpansion.getPlugin(), "eternal");
    public static NamespacedKey grimsteel = new NamespacedKey(AdventureExpansion.getPlugin(), "grimsteel");
    public static NamespacedKey dragonhide = new NamespacedKey(AdventureExpansion.getPlugin(), "dragonhide");
    public static NamespacedKey heartAmulet = new NamespacedKey(AdventureExpansion.getPlugin(), "heart_amulet");
    public static NamespacedKey stew = new NamespacedKey(AdventureExpansion.getPlugin(), "stew");
    public static NamespacedKey ender = new NamespacedKey(AdventureExpansion.getPlugin(), "ender");
    public static NamespacedKey enderShield = new NamespacedKey(AdventureExpansion.getPlugin(), "ender_shield");
    public static NamespacedKey endersWake = new NamespacedKey(AdventureExpansion.getPlugin(), "enders_wake");
    public static NamespacedKey wolfHead = new NamespacedKey(AdventureExpansion.getPlugin(), "wolf_head");
    public static NamespacedKey sculkBoots = new NamespacedKey(AdventureExpansion.getPlugin(), "sculk_boots");
    public static NamespacedKey itemMagnet = new NamespacedKey(AdventureExpansion.getPlugin(), "item_magnet");
    public static NamespacedKey expMagnet = new NamespacedKey(AdventureExpansion.getPlugin(), "exp_magnet");
    public static NamespacedKey witherBow = new NamespacedKey(AdventureExpansion.getPlugin(), "wither_bow");
    public static NamespacedKey evokerBow = new NamespacedKey(AdventureExpansion.getPlugin(), "evoker_bow");
    public static NamespacedKey bountyBow = new NamespacedKey(AdventureExpansion.getPlugin(), "bounty_bow");
    public static NamespacedKey minersHat = new NamespacedKey(AdventureExpansion.getPlugin(), "miners_hat");
    public static NamespacedKey shadowCrown = new NamespacedKey(AdventureExpansion.getPlugin(), "crown_of_shadows");
    public static NamespacedKey wandOfIndecision = new NamespacedKey(AdventureExpansion.getPlugin(), "wand_of_indecision");
    public static NamespacedKey traderHat = new NamespacedKey(AdventureExpansion.getPlugin(), "trader_hat");
    public static NamespacedKey travelerHelmet = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler_helmet");
    public static NamespacedKey travelerChestplate = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler_chestplate");
    public static NamespacedKey travelerLeggings = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler_leggings");
    public static NamespacedKey travelerBoots = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler_boots");
    public static NamespacedKey travelerSword = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler_sword");
    public static NamespacedKey travelerPickaxe = new NamespacedKey(AdventureExpansion.getPlugin(), "traveler_pickaxe");
    public static NamespacedKey raiderHelmet = new NamespacedKey(AdventureExpansion.getPlugin(), "raider_helmet");
    public static NamespacedKey raiderChestplate = new NamespacedKey(AdventureExpansion.getPlugin(), "raider_chestplate");
    public static NamespacedKey raiderLeggings = new NamespacedKey(AdventureExpansion.getPlugin(), "raider_leggings");
    public static NamespacedKey raiderBoots = new NamespacedKey(AdventureExpansion.getPlugin(), "raider_boots");
    public static NamespacedKey raiderSword = new NamespacedKey(AdventureExpansion.getPlugin(), "raider_sword");
    public static NamespacedKey raiderPickaxe = new NamespacedKey(AdventureExpansion.getPlugin(), "raider_pickaxe");
    public static NamespacedKey awakenedHelmet = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened_helmet");
    public static NamespacedKey awakenedChestplate = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened_chestplate");
    public static NamespacedKey awakenedLeggings = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened_leggings");
    public static NamespacedKey awakenedBoots = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened_boots");
    public static NamespacedKey awakenedSword = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened_sword");
    public static NamespacedKey awakenedPickaxe = new NamespacedKey(AdventureExpansion.getPlugin(), "awakened_pickaxe");
    public static NamespacedKey eternalHelmet = new NamespacedKey(AdventureExpansion.getPlugin(), "eternal_helmet");
    public static NamespacedKey eternalChestplate = new NamespacedKey(AdventureExpansion.getPlugin(), "eternal_chestplate");
    public static NamespacedKey eternalLeggings = new NamespacedKey(AdventureExpansion.getPlugin(), "eternal_leggings");
    public static NamespacedKey eternalBoots = new NamespacedKey(AdventureExpansion.getPlugin(), "eternal_boots");
    public static NamespacedKey calamity = new NamespacedKey(AdventureExpansion.getPlugin(), "calamity");
    public static NamespacedKey calamitySword = new NamespacedKey(AdventureExpansion.getPlugin(), "calamity_sword");
    public static NamespacedKey mobSpawner = new NamespacedKey(AdventureExpansion.getPlugin(), "mob_spawner");
    public static NamespacedKey dragonhideHelmet = new NamespacedKey(AdventureExpansion.getPlugin(), "dragonhide_helmet");
    public static NamespacedKey dragonhideChestplate = new NamespacedKey(AdventureExpansion.getPlugin(), "dragonhide_chestplate");
    public static NamespacedKey dragonhideLeggings = new NamespacedKey(AdventureExpansion.getPlugin(), "dragonhide_leggings");
    public static NamespacedKey dragonhideBoots = new NamespacedKey(AdventureExpansion.getPlugin(), "dragonhide_boots");
    public static NamespacedKey pityTrophy = new NamespacedKey(AdventureExpansion.getPlugin(), "pity_trophy");
    public static NamespacedKey gonk = new NamespacedKey(AdventureExpansion.getPlugin(), "gonk");
}
